[package]
name = "wow"
version = "0.1.0"

[[bin]]
path = "src/main.rs"
name = "wow"

[dependencies]
serde_yaml = "0.7.3"
serde_derive = "1.0.37"
serde = "1.0.37"
mkdirp = "0.1.0"
crypto-hash = "0.3.1"
hex-slice = "0.1.4"
plist = "0.2.4"
tempfile = "3.0.0"
quick-error = "1.2.1"
target = "1.0.0"
